### ISSUE TITLE
Describe Phase II deliverables and how we will publish them

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/DevFlow#33]
add a working list in table view using md
- [ ] Finalize list of deliverables to update or add in Phase II
- [ ] For each, formalize where they are stored and how included in repository
- [ ] Draft Template shells for each and inlcude an issue for each with links to the files

**Comment by rudimusmaximus** [comment]
Each deliverable will have it's own issue to track completion.
It will be stored on RCM Drive Space as a G Suite doc
Finished versions will be 'snapshoted as pdf' and also linked.
Also, pdfs will be posted to project page as deliverables.
Videos where applicable will be posted in drive with link embed to project site.
The documents will continue as living documents in Phase II and ongoing.

**Comment by RobGoelz** [comment]
| Deliverable | Issue Number | Assignee | Due Date | Completed (y/n) |
|-------------|--------------|----------|----------|-----------------|
|             |              |          |          |                 |
|             |              |          |          |                 |
|             |              |          |          |                 |

**Comment by RobGoelz** [comment]
see this helpful MD generator for tables:
https://www.tablesgenerator.com/markdown_tables

**Comment by RobGoelz** [comment]
see this helpful MD generator for tables:
https://www.tablesgenerator.com/markdown_tables

**Comment by rudimusmaximus** [comment]
That’s good. Drop assignee and due date add description and toc.

**Comment by RobGoelz** [comment]
| Deliverable               | Issue Number | Due Date | Description                          | TOC | Completed (y/n) | Snapshot PDF (y/n) |
|---------------------------|:------------:|:--------:|--------------------------------------|-----|:---------------:|:------------------:|
| Template for Q&A Question |      35      |          | Provides template format for issues. |     |        Y        |          N         |
|                           |              |          |                                      |     |                 |                    |
|                           |              |          |                                      |     |                 |                    |
|                           |              |          |                                      |     |                 |                    |

**Comment by RobGoelz** [comment]
updated with sample Issue, see above

**Comment by rudimusmaximus** [comment]
That works. change Description to purpose and review our private doc [here](https://docs.google.com/spreadsheets/d/1nJUMsLTO7Hi8ojpNEoN6lvlWBZuX468fNIQzosr_m78/edit#gid=0) to brainstorm what we need; i took a pass at highlighting row 1 and column E for candidates. we can work out of that and as we flush out the details move them to the table you have here and create issues with their design infor to include what's on our private inventory.
If you have time to review the sheet items that were highlighted; prob need to add field for snapshot links and section for such on those items that link to drive files.
Two heads better than one. Thanks.

**Comment by rudimusmaximus** [comment]
mabye change your TOC to Link (repo if issue only, repo and drive if also)

**Comment by rudimusmaximus** [comment]
# How's this?
 - We can merge a status and completion indicator in the one Due Date column.
 - Status in *italics* can be `Not Started`, `Work In Progress`, `On Hold`, `Cancelled`; Completed items get a date also  in *italics*.
 - Link(s) are to Issues, Deliverable on drive, and PDF Snapshots.  

| Deliverable Short Title | Due Date [*Delivered or Status*] | Purpose | Comments | Link(s) |
|:---|:---|:---|:---|:---|
| **Template for Q&A Question** |    5/12/2018 [*5/9/2018*]      | Provides template format for questions, filed as issues. |  Issue only | [Issue  35](https://github.com/rudimusmaximus/DevFlow/issues/35), [No PDF 2018.05.21](google.com)   |
| **Template for a DevFlow Issue that's code related** | 5/14/2018 [*completed add date*] |  Provides default issue template to be used for code issues created in a Glo board. | Issue only | [Issue  43](https://github.com/rudimusmaximus/DevFlow/issues/43), [No PDF 2018.05.21](google.com) |  
| **tbd** | mm/dd/yyyy [*not started*] | tbd | Issue, Lucid Chart Diagram, Keynote Presentation, | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |
| **tbd** | mm/dd/yyyy [*not started*] | tbd | | [Issue tbd ](google.com), [Deliverable](google.com), [PDF 2018.mm.dd](google.com) |

not sure if multiple links in a single cell is an issue, but here's this for comment. see you wed.

**Comment by rudimusmaximus** [comment]
- [ ] let's update this to the q&a format, add link to new version of sheet just for this purpose.
