### ISSUE TITLE
How can I keep up with Weekly Wednesdays I can't attend?

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/DevFlow#46]
# How to keep up with Weekly Wednesdays
Need a place to catch up.
# Final Answer
We are driving to put 'everything' into the repo and keep up to date via Glo Board.
Here is a [direct link to the web app for this board](https://app.gitkraken.com/glo/board/WuiAgk8ztxUAEknp)    
Notes from meetings will be logged Markdown style in updates to this issue here in chronological order.
Meetings will be on Wednesdays and either be a working session, a general session or combination of the two:  
 - **Working Sessions by topic**
 - **General Sessions for demonstrating the state of the project**

Key Completed:
- [x] Kicked off lead only meetings, kicked off weekly meetings
- [x] Start a logging issue for Weekly Wednesdays; #46 this issue
- [x] Send glo board invites to rest of email list that have not updated for phase II but have left subscription on  
- [x] GAS basics parts 1-3: cover more examples as described in the last section of Gist linked to [issue 45](https://github.com/rudimusmaximus/DevFlow/issues/45)
- [x] Conduct first and second general sessions  
- [x] Conducted General Session II (and GAS part 3 working session) 
- [x] Started a timeout on July 12
- [x] **Aug 15, 2018** General Session III CANCELED
- [x] **Aug 22nd** resume weekly Wednesday working sessions - more GAS and addon prep
- [x] started ZenHub SPRINT 1 - Aug 22 - Sep 5 14day sprint
- [x] Demonstrate release push with develop branch demo of make test ready
- [x] Standup basic published to shareable unlisted link
- [x] **Sep 12, 2018** General Session 4 - Basic addon ready demo, demo ideas  

Key Upcoming:
- [x] **Sep 19** - Claim or lose a demo by commenting on issue #65 
- [x] **Dec 12** - Phase II Closed - Demo, lessons learned, comments on phase III  
- [ ] **tbd** - Phase III Open Sprints as scheduled  
- [ ] Best Practices Sprint - Open source facelift on our readme and repo to model collaboration and update everything after lessons learned, readme.md, issues and epics for updated release intent

# Overall Plan dates
Leads with access to maintain a high-level plan. The main dates are above.  

## Latest Plan Extract  
Our website hosts the latest and most detailed publically available plan is on our site.
[See our project site](devflow4fewd.redcrowmethods.com)  

# Chronological Notes  
Abbreviations:
 - **WS** Weekly Wednesday Working Session
 - **GS** 2nd Wednesday General Session  
 
## 2018.05.09 WS-Planning Meeting
 - No recording  

## 2018.05.16 WS-Overview and GAS Basics part one  
 - Overview of boards and approach with a review of the current timeline.
 - [Recording of the session is available here at this link](https://drive.google.com/a/redcrowconsulting.com/file/d/13L7PuhbZ0AIHOxp0R0esjWSi5z4D5Tqg/view?usp=sharing).  
 - GAS basics covered outline of [this Gist](https://gist.github.com/rudimusmaximus/bfe0ac7ca872bb0b2f8a7cb30a524eff) mentioned in [issue #45](https://github.com/rudimusmaximus/DevFlow/issues/45)

## 2018.05.23 WS-Debug and tested make test ready no recording  
 - Make test ready is develop branch at the next session we will test it and move it to production live; [read about it in issue 8](https://github.com/rudimusmaximus/DevFlow/issues/8)
 - Two great tools used to create issue 8 documentation were:
   - [Dillinger as recommended by Udacity](https://dillinger.io/) 
   - [Markdown Table Maker for Google Sheets](https://chrome.google.com/webstore/detail/markdowntablemaker/cofkbgfmijanlcdooemafafokhhaeold?utm_source=permalink)

### Agenda  
 - Project schedule udpates
 - Out of Sync workaround
 - Linking to other issuses on GloBoard
 - Deliverables for phase II
   - See #33 [...DevFlow/issues/33](https://github.com/rudimusmaximus/DevFlow/issues/33)
 - Make Test Ready Process
   - See #8 [...DevFlow/issues/8](https://github.com/rudimusmaximus/DevFlow/issues/8)
   - See #48 [...DevFlow/issues/48](https://github.com/rudimusmaximus/DevFlow/issues/48)
 - cool articles:
   - [CSS Grid vs Flexbox](https://hackernoon.com/the-ultimate-css-battle-grid-vs-flexbox-d40da0449faf)
 - udpates on GitKraken Glo board software
   - no action required; just added pdf of correspondence so you can see how we campaign for features we want. Sometimes, it's better to influence young or responsive products to get what you need rather than build your own tools.  [Correspondence](https://drive.google.com/a/redcrowconsulting.com/file/d/17rTil06YdsS8mvkU566BjeLXXNiSVW3R/view?usp=sharing)  
   - See also #40 [...DevFlow/issues/40](https://github.com/rudimusmaximus/DevFlow/issues/40)  

### Agenda with notes  
 - **make test ready** was released in DevFlow v0.4.0 and is in both Develop and Master branches.
   - we are working out an issue discovered in testing around newly re-named scripts; we will make an edit to logging and the process write-up. They will go in as a 'hotfix' to demonstrate that too. We will demo result in our first general session on June 13th.
 - **General session I June 13, 2018, 1 of 5 in Phase II**
   - In each of these sessions, we will present a presentation on the approach and deliverables highlighting updates since the last meeting
   - Demo make test ready
   - updates to Deliverables for phase II
      - See #33 [...DevFlow/issues/33](https://github.com/rudimusmaximus/DevFlow/issues/33)
      - TODO: finish adding a list of deliverables
      - TODO: generate issues for each of these deliverables
 - **This week's Cool links**:
   - [Placeholder Image Tool](https://placeholder.com)  "Quick & simple image placeholders" you can set format, text color and size in a single URL, use in code or to generate what you need. change to https if needed.
   - [Insert Icons for Google Slides](https://chrome.google.com/webstore/detail/insert-icons-for-slides/ebobdijloifekdgihhibghageadfgbml)
   - [Insert Icons for Google Docs](https://chrome.google.com/webstore/detail/insert-icons-for-docs/ihdckhgffclpplbgdlhmbdhmjmlhpbnd)
 - **Next Week:**  So far, we've worked out of emails and issue updates on the repo via glo board. BE ON THE LOOKOUT for placeholder meeting invites for each of the 5 monthly general sessions.  

## 2018.06.13 GS-General Session I and Special Guest   

 **Agenda:** special guest from at&t scheduled to join us!
  1 State of the repo and release updates
  2 Phase II our "deliverables" updates - repo documents to model the DevFlow approach
  3 State of the Demos updates - when started
  4 Session Highlight - Make Test Ready process, Glo Boards show and tell demo with lessons learned
  5 Q&A - Open questions and hands-on

 **Notes:**
 Here's [the presentation PDF with live links](https://drive.google.com/a/redcrowconsulting.com/file/d/1A_TQQrvJCkXmNvUQ-RUdLql8hFNqBmQr/view?usp=sharing) AND [the recorded session of 1hr30m](https://drive.google.com/a/redcrowconsulting.com/file/d/1AdwJQGwDuSErwjzrc8CC2J9q6YnT7vjQ/view?usp=sharing).
 Hear from our at&t guest at the end after the demo.
   
 
### Agenda with notes  
 - **GAS Basics** working sessions to try out GAS on sheets data; some of these could be turned into demos of successful "GAS patterns"
   - Each week for a series of weeks will cover some GAS basics and share the sheet with its script as well as the recording, so you can follow along and explore.
   - We recommend making a copy of the provided files and then working from there. If you want to make comments on the file, just add comments in the sheet we link you to.
 - **Topics covered include**
   - Update Multiple Values
   - Manipulate Disjoint Ranges
   - joint discovery based on interest and time
        - on open build menu calling these
        - others? practice using and presenting from editor
    - dates - cancelling working session on Aug 1st
 - **This week's Cool links**:
   - [Working Sheet File w Script](https://docs.google.com/spreadsheets/d/1OGKaMNs1zJwemzGyWci1dG_Q2e1FH7-N-j5DcOkv8GY/edit?usp=sharing)  
   - [How Fast is Realtime? Human Perception and Technology](https://www.pubnub.com/blog/how-fast-is-realtime-human-perception-and-technology/)  
   - [JavaScript engine fundamentals: Shapes and Inline Caches](https://mathiasbynens.be/notes/shapes-ics)
      - the original tweet about the article has a rich discussion [see Twitter post](https://twitter.com/mathias/status/1007524406728458241)  
    - [The One Tab chrome and firefox extension](https://chrome.google.com/webstore/detail/onetab/chphlpgkkbolifaimnlloiipkdnihall) save 95% of memory when you have too many tabs open; use as intended
    - [Digo Chrome Extension](https://www.diigo.com/tools/chrome_extension) extension for Diigo.com tool

 - **Unassigned Action Items:** research items, problems to solve, notes, special items
     - [Other DevFlows from GDEs](https://plus.google.com/+AndrewRoberts1/posts/AZsgxBpLvcq?fscid=z13xevizsoabsvadt23ucjfb1vyfcboic04.1529332593935425) we gave feedback (and got mentioned) in a google developer expert's DevFlow for an org team. This G+ post shows him listing a document for feedback and the document itself has comments you can review in comment mode. He has a great idea about including manifest files (more later). IF you are ever keen and the post is still up, check it out for a look at open collaboration about methods.  
        - [OUR copy of doc with comments](https://docs.google.com/document/d/1NJr4v37OWnj4bBs6B7h2UK3dfM-h3pukeaiHfSI-L3s/edit?usp=sharing) open the comments thread...feel free to comment on this one for our internal use
     - [ ] ideas for GAS series working sessions
         - [x] use the "Gist query my sheet" demo to build a 2d array from sheet data
            -[ ] try out a few patterns on this data
         - [ ] PhaseII? - grab real problems posed in G+ for discussion; for example, [this one](https://plus.google.com/+JacobMcAlisterMIW/posts/a11LzQoafRh) has a recommended solution where the answer involves a simple and an installable trigger. Triggers might be a topic
            - setup a series to solve, then work the list practicing working in GAS
         - [ ] Incorporate manifests so required services are more clear and GAS GitHub assistant pulls them as well. This is a js file you can make visible in the web GAS editor. Review also Other DevFlows from GDEs in GAS Basics Part 1 notes as it was their suggestion  
 - **Next Week:** part 2  

### Agenda with notes  
 - **GAS Basics** working sessions to try out GAS on sheets data; some of these could be turned into demos of successful "GAS patterns"
   - UPDATED approach, use the new repo to get the code and add it to a fresh sheet.
 - **Topics covered include**
   - Review great links
   - Create a new repo for this "BurningGAS"
       - Pull in last weeks two functions and onOpen menu in a new repo
       - modify to create the input sheets
    - Gist query my sheet build
 - **This week's Cool links**:
     - [our new repo for these GAS sessions](https://github.com/rudimusmaximus/BurningGAS)
     - Check the learning GIST for these two new links; we will likely pull the GIST into our new repo
         - This great [gist by Amit Agarwal](https://gist.github.com/labnol/0b67f812a827fd9babc5)  
         - For tutorials covering the basics, check out [The website of Barrie Roberts](https://www.bazroberts.com/category/apps-script/) 
     - [explore these sources for data to use, especially 5](https://www.sba.gov/blogs/conducting-market-research-here-are-5-official-sources-free-data-can-help)
     - [Looking for data? Try Kaggle](https://www.kaggle.com/)
        - [Datasets](https://www.kaggle.com/datasets)
        - [KAGGLE example 'google job skills'](https://www.kaggle.com/niyamatalmass/google-job-skills)
     - [Javascript Linter Online tool](jshint.com)
     - atom plug in options
        - [Javascript Linter in Atom](https://atom.io/packages/atom-jshint)
        - [Javascript Linter in Atom](https://atom.io/packages/jshint)
     - [next week's topic](https://gist.github.com/rudimusmaximus/133ef10736888e42f0c9ba89c07be546)
 - **Next Week:** part 3  
 
## 2018.07.04 WS-GAS Basics Part 3
Canceled due to holiday; merging with General Session II.  

### Agenda with notes  
 - **GAS Basics** working sessions to try out GAS on sheets data; some of these could be turned into demos of successful "GAS patterns"
 - **Topics covered include**
   - Catch up on the gas workshops via the video links and 
     - [our new repo for these GAS sessions "BurningGas"](https://github.com/rudimusmaximus/BurningGAS)
   - Demo 'Gist query my sheet' shows SQL like query to a 2d array and use of advanced sheet service to right-size the new sheet with the exact number of rows and columns required
   - demonstrate GitHub /compare feature
       - 1.1.0 Gist query my sheet "make it possible"
       - 1.1.1 Faster - batching more actions for speed "make it faster"
       - 1.1.2 Functional - slightly slower for a reason, leveraging API best practices and workarounds "make it pleasant" for the first run, re-run

 - **This week's Cool links with a few more added for time off**:
     - [the importance of speed](https://www.hobo-web.co.uk/your-website-design-should-load-in-4-seconds/)  Incredible information here.
     - [Designer vs. Developer YouTube series](https://www.youtube.com/playlist?list=PLNYkxOF6rcIC60856GnLEV5GQXMxc9ByJ) - Designer vs. Developer aims to provide takeaways, solutions to workflows, tools & discussions on everyday struggles. **Especially check out the notes for links.** For example, #17 "Using Gestalt Principles to Improve Your Design" mentions these two gems among others
         - [Gestalt laws of grouping](http://bit.ly/2tNUqpr)  
         - [Universal Principles of Design](http://universalprinciplesofdesign.com/)
             - [Becoming Leonardo: How Great Designers Think on youtube free](https://www.youtube.com/watch?v=rdH8Kuku9tA)
     - [revered article on javascript patterns with modules](http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html)  
     - **replay of Google's App Maker panel session** [Totally Unscripted panel on App Maker Questions](https://plus.google.com/+TotallyUnscriptedShow/posts/enTWZ3dUPTm)
     - [dotfiles](https://dotfiles.github.io/) Your unofficial guide to dotfiles on GitHub. **Let's discuss if we need to define this as part of our setup and config or an open call for tools that do this** 
     - [A deep set of highly competent content for GAS skills](https://plus.google.com/+KanshiTanaike/posts/99HfmGLDJY3) This person's work is amazing. Go deeper with the links and learn lots.
     - [Google Apps Developer Series: How to Increase Traffic to your Add-On With AppsScript](https://www.youtube.com/watch?authindex=0&v=vToNpuLiMHE) Inventor of GAS gives addon advice, originally a Cloud Connect Live Event Streamed live on Jun 2, 2015. Great material. Also, they mention which javascript engine is being used!
     - [Using Google Apps Script to automate G Suite (Google Cloud Next '17)](https://www.youtube.com/watch?v=vBsIYZEqjTA) This more recent walkthrough has a very good and straightforward set of code examples in their presentation. Especially look for stubbing of services for testing in the Gmail example and the use of templated HTML with regard to the use of escaped javascript in the html file in the web app section - not sure if the second one is best practice or not but it's interesting.

 - **Next Week:** IMPORTANT TIME OFF MESSAGE
     - Taking time off to catch up with coursework. **General Session 3 Canceled!**
     - **No working sessions until 2018 Aug 22**
     - General Session 4 on **Sep 12th** will demo our version of the addon and will be a good one to attend as we will be ready to share demo credit if you can take one after seeing how we lay them out
     - **Demos for phase II will be assigned by the end of working session Sep 19th...."claim your demo or lose it for phase II :)"**

### Agenda with notes  
 - **our add-on** working sessions to prep our addon so volunteers can add demos
 - **Topics covered include**
   - Setup 14-day sprint on ZenHub  
     - prep ZenHub SPRINT 1 - Aug 22 - Sep 5
     - skeleton only, we will add detail as possible
   - Start work
   - GitKraken has many great updates, so make sure you have latest. Like syntax highlighting and a code editor inside the interface https://www.gitkraken.com/git-client#code-editor 
 
 - **This week's Cool links**:
     - [Automating G Suite: Apps Script & Sheets Macro Recorder (Cloud Next '18)](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fyoutu.be%2FMGkcbP5Gd1o) - Nice overview
     - [Excellent summary of changes from Next](http://flip.it/kRFPj0) - also has links for training like on clasp
     - [Community talk about clasp](https://plus.google.com/109179308055912434363/posts/SA19Sb3WeoE) - discussions on getting clasp ready for our use, but we are held up with the issue of renaming .gs into .js which doesn't work for us just yet
     - [Clasp](https://github.com/google/clasp) - start this open source repo so you can keep track of it
     - [Good article, from a straight shooter](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fcharity.wtf%2F2018%2F08%2F19%2Fshipping-software-should-not-be-scary%2F) - check out her blog and work as well
 - **Upcomming:** 
    - Shakeout our first sprint from Aug 22 - Sept 5, 2018
    - General Session 4 on **Sep 12th** will demo our version of the addon and will be a good one to attend as we will be ready to share demo credit if you can take one after seing how we lay them out
     - **Demos for phase II will be assigned by the end of working session Sep 19th...."claim your demo or lose it for phase II :)"**

### Agenda with notes  
 - **our add-on** working sessions to prep our addon so volunteers can add demos.
     - Shakeout our first sprint from Aug 22 - Sept 5, 2018
 - **Topics covered include**
   - Continue ZenHub sprint, update issues
   - Permissions on repo and adding a collaborator
   - use Placeholder.com to create our marketing tiles for the welcome, and example first demo
   - per G guidelines we need the following for our store listing (even if publishind to group or domain)
       - Small tile - 440x280
       - Large tile - 920x680
       - Marquee - 1400x560
   - We will need to resolve how we want to handle the small addon icon with a 96x96 internal symbol (see google guidelines) Guidelines for  square icon: 96x96pixels for the art inside and 128x128 pixels overall
   - We will submit files for the 'market listing' top level, but for each demo you can use these for now by reference.
       - https://via.placeholder.com/440x280?text=SmallTile
       - https://via.placeholder.com/920x680?text=LargeTile
       - https://via.placeholder.com/1400x560?text=Marquee

 - **This week's Cool links with a few more added for time off**:
     - next week will share again the UI guidelines and the market listing instructions
     - for example [see icon section](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fdeveloper.chrome.com%2Fwebstore%2Fimages%3Fhl%3Den%23promo)
 - **Upcomming:** 
    - General Session 4 on **Sep 12th** will demo our version of the addon and will be a good one to attend as we will be ready to share demo credit if you can take one after seing how we lay them out
     - **Demos for phase II will be assigned by the end of working session Sep 19th...."claim your demo or lose it for phase II :)"**  

## 2018.09.05 WS-Addon Standup  
No recording. Working session.
Hot links include incorporating Clasp see #62.

## 2018.09.12 GS-Demo state of Addon Standup, highlight sprint lessons learned, demo ideas 
[RECORDING](https://drive.google.com/a/redcrowconsulting.com/file/d/1-Zk3UCkDyrGGtEOHRraOVzU9eBmxPToy/view?usp=sharing)
[PRESENTATION](https://drive.google.com/a/redcrowconsulting.com/file/d/1-_dVZxZpHXOuugIf66pFQ8BzGH8PyW3B/view?usp=sharing)
### Agenda
 - install of the unlisted add-on
 - two demos
 - full demonstration of what the workflow looks like from feedback to publishing a change 
 - a code walkthrough of how the add-on works

If you want to do a demo, let us know by saying so on issue 46 by Wed the 19th. State which one and whether you'd like to get it done before next General Session on second Wednesday in Oct or during phase III and we will reserve it for you. Two easy and a third possible, others will be in Phase III. Watch the vid, pick one if you want. Contributors get their pic and LinkedIn included as part of the demo AND can say they contributed to an open source project.
   - Update multiple cells (from BurningGAS example)
   - Manipulate disjoint ranges (from BurningGAS example)
   - What's new (from Totally Unscripted, if the creator doesn't want to do it)
Working sessions by appointment, otherwise next session will be Oct 11, 2018, to close Phase II 

## 2018.12.12 GS-General Session: Phase II Lessons Learned   

 **Agenda:**
  - State of the repo and release updates
  - State of the repo and release updates
  - Lessons Learned and Feedback summary
  - Phase III plans
  - What to do next  
  
 **Notes:**
**1 Here's [the presentation PDF with live links](https://drive.google.com/open?id=1t35z9Vvc1V66HM0FlIx0CBEfTnPafsbm) AND [the recorded session of 41m 30s](https://drive.google.com/a/redcrowmethods.com/file/d/1o4i3zeHoDI1ozyPe_ueLF23U2s70opLF/view?usp=sharing)**.  
**2 Be sure and also check the pdf slides as we added a little content after the meeting.**  
**3 Phase III is OPEN TO THE PUBLIC (more to come)**  
**4 Feedback themes**
  - Themes - focus/audience, amount of content, complexity of content, there is a value to create and deliver
  - We made Alexander Ivanov’s google apps script awesome list
  - we are #3 in a current google search!
  - Feedback from G+ Moderators  
 
**5 Rudy's notes on organizing principles of getting good at something B/H, C, M**
**B/H - behavior the critical success factors** 
figure out what they are, make them your habits, observe the best you can find, follow critical content creators on twitter, pay attention 

**C - competence**
many kinds/domains (this is the stuff of methodologies) examples of competence/acumen include - technical, professional, business, others…
in your career you will generally be working on maybe 4-8 that you should master (check that number, i’m just throwing that out there)
rating competence - if on a scale of 1-5; 1 would be newly trained and 5 might be gets paid to present or published content for sale

**M-mastery**
10,000hrs + continual learning
a good motto borrowed from martial arts “we need more practice”

**6 Closing notes**  
Rob and I will be working on DevFlow as an ongoing open source with attribution project. So keep watching the space. Also, you can now watch for release updates.

**Startup activities:**
Additionally, I applied for the ND to learn how to make my own prototypes and help me in bootstrapping a startup.
If you want to learn about that, get to know us through the DevFlow project first.
If your company is looking to establish a GAS team using DevFlow, please reach out as I might be doing some of that in the new year as well.
**7 Next items** 
 - Star and watch releases of [DevFlow](https://github.com/rudimusmaximus/DevFlow),  [BurnginGAS](https://github.com/rudimusmaximus/BurningGAS), and any issues/epics you like
 - [Install the private link to our google sheets add-on](https://drive.google.com/file/d/12zMiDLJH2PKY6ccwVv65xLvTxBKJs74h); play with it with overtime when there are new releases
 - Exlpore [the resource link hosted on diigo](https://www.diigo.com/outliner/ggv9dd/DevFlow-Phase-II-Lessons-Learned-Phase-III-Plans?key=q9ofbdcsfd)
SEE YOU IN 2019!!!!!!!

# Have a question or comment? 
Add it to this issue history in a new comment block and mention TODO or TODO. Thanks.

**Comment by rudimusmaximus** [comment]
# Working Session Notes
## todo: update previous
## 2018.05.16 Overview and GAS Basics part one  
Overview of boards and approach with review of current timeline.
[Recording of session available here at this link](https://drive.google.com/a/redcrowconsulting.com/file/d/13L7PuhbZ0AIHOxp0R0esjWSi5z4D5Tqg/view?usp=sharing).  
GAS basics covered outline of Gist in issue #45
TODO: cover more examples as described in last section of Gist.

**Comment by rudimusmaximus** [comment]
# General Session Notes
## Jun Second Wednesday  
## Jul Second Wednesday  
## Aug Second Wednesday  
## Sep Second Wednesday  
## Oct Second Wednesday

**Comment by rudimusmaximus** [comment]
@ImNotGil weekly updates are in this issue with links to recordings when possible

**Comment by RobGoelz** [comment]
Check out this link on how to import from bookmarks into diigo:
https://www.diigo.com/tools/import_all

**Comment by RobGoelz** [comment]
Search for OneTab in chrome extensions - excellent tool

**Comment by rudimusmaximus** [comment]
Revised notes in the main section and made notes, chronological, added notes from last working session and included dates for time out and list of work to complete for phase II. Thanks, See you Aug 22nd. @RobGoelz let me know if anything is off. I'll send a note out.

**Comment by rudimusmaximus** [comment]
Notes updated with Aug 29 notes and recording link. Next week working session likely no recording. See you at general session in 2 weeks

**Comment by rudimusmaximus** [comment]
Updated notes for 2018.12.12 GS-General Session: Phase II Lessons Learned

**Comment by rudimusmaximus** [comment]
We will be rebooting in the coming months. A new company email list can be found here.
http://bit.ly/rcc-signup
Thanks for your patience.
